/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedViagensRouteImport } from './routes/_authenticated/viagens'
import { Route as AuthenticatedRelatorioRouteImport } from './routes/_authenticated/relatorio'
import { Route as AuthenticatedRastreadorRouteImport } from './routes/_authenticated/rastreador'
import { Route as AuthenticatedMotoristasRouteImport } from './routes/_authenticated/motoristas'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedManutencaoRouteImport } from './routes/_authenticated/manutencao'
import { Route as AuthenticatedLugaresRouteImport } from './routes/_authenticated/lugares'
import { Route as AuthenticatedGestaoRouteImport } from './routes/_authenticated/gestao'
import { Route as AuthenticatedEcoRouteImport } from './routes/_authenticated/eco'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedAjustesRouteImport } from './routes/_authenticated/ajustes'
import { Route as AuthenticatedAbastecimentoRouteImport } from './routes/_authenticated/abastecimento'
import { Route as ApiPublicTrackerHeartbeatRouteImport } from './routes/api/public/tracker-heartbeat'
import { Route as ApiPublicFlespiWebhookRouteImport } from './routes/api/public/flespi-webhook'
import { Route as AuthenticatedViagensIdRouteImport } from './routes/_authenticated/viagens.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedViagensRoute = AuthenticatedViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioRoute = AuthenticatedRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRastreadorRoute = AuthenticatedRastreadorRouteImport.update({
  id: '/rastreador',
  path: '/rastreador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotoristasRoute = AuthenticatedMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManutencaoRoute = AuthenticatedManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLugaresRoute = AuthenticatedLugaresRouteImport.update({
  id: '/lugares',
  path: '/lugares',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGestaoRoute = AuthenticatedGestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEcoRoute = AuthenticatedEcoRouteImport.update({
  id: '/eco',
  path: '/eco',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjustesRoute = AuthenticatedAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAbastecimentoRoute =
  AuthenticatedAbastecimentoRouteImport.update({
    id: '/abastecimento',
    path: '/abastecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTrackerHeartbeatRoute =
  ApiPublicTrackerHeartbeatRouteImport.update({
    id: '/api/public/tracker-heartbeat',
    path: '/api/public/tracker-heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFlespiWebhookRoute = ApiPublicFlespiWebhookRouteImport.update({
  id: '/api/public/flespi-webhook',
  path: '/api/public/flespi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedViagensIdRoute = AuthenticatedViagensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedViagensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/abastecimento': typeof AuthenticatedAbastecimentoRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/eco': typeof AuthenticatedEcoRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/lugares': typeof AuthenticatedLugaresRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/motoristas': typeof AuthenticatedMotoristasRoute
  '/rastreador': typeof AuthenticatedRastreadorRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/viagens': typeof AuthenticatedViagensRouteWithChildren
  '/viagens/$id': typeof AuthenticatedViagensIdRoute
  '/api/public/flespi-webhook': typeof ApiPublicFlespiWebhookRoute
  '/api/public/tracker-heartbeat': typeof ApiPublicTrackerHeartbeatRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/abastecimento': typeof AuthenticatedAbastecimentoRoute
  '/ajustes': typeof AuthenticatedAjustesRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/eco': typeof AuthenticatedEcoRoute
  '/gestao': typeof AuthenticatedGestaoRoute
  '/lugares': typeof AuthenticatedLugaresRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/motoristas': typeof AuthenticatedMotoristasRoute
  '/rastreador': typeof AuthenticatedRastreadorRoute
  '/relatorio': typeof AuthenticatedRelatorioRoute
  '/viagens': typeof AuthenticatedViagensRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/viagens/$id': typeof AuthenticatedViagensIdRoute
  '/api/public/flespi-webhook': typeof ApiPublicFlespiWebhookRoute
  '/api/public/tracker-heartbeat': typeof ApiPublicTrackerHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/abastecimento': typeof AuthenticatedAbastecimentoRoute
  '/_authenticated/ajustes': typeof AuthenticatedAjustesRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/eco': typeof AuthenticatedEcoRoute
  '/_authenticated/gestao': typeof AuthenticatedGestaoRoute
  '/_authenticated/lugares': typeof AuthenticatedLugaresRoute
  '/_authenticated/manutencao': typeof AuthenticatedManutencaoRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/motoristas': typeof AuthenticatedMotoristasRoute
  '/_authenticated/rastreador': typeof AuthenticatedRastreadorRoute
  '/_authenticated/relatorio': typeof AuthenticatedRelatorioRoute
  '/_authenticated/viagens': typeof AuthenticatedViagensRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/viagens/$id': typeof AuthenticatedViagensIdRoute
  '/api/public/flespi-webhook': typeof ApiPublicFlespiWebhookRoute
  '/api/public/tracker-heartbeat': typeof ApiPublicTrackerHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/abastecimento'
    | '/ajustes'
    | '/despesas'
    | '/documentos'
    | '/eco'
    | '/gestao'
    | '/lugares'
    | '/manutencao'
    | '/mapa'
    | '/motoristas'
    | '/rastreador'
    | '/relatorio'
    | '/viagens'
    | '/viagens/$id'
    | '/api/public/flespi-webhook'
    | '/api/public/tracker-heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/abastecimento'
    | '/ajustes'
    | '/despesas'
    | '/documentos'
    | '/eco'
    | '/gestao'
    | '/lugares'
    | '/manutencao'
    | '/mapa'
    | '/motoristas'
    | '/rastreador'
    | '/relatorio'
    | '/viagens'
    | '/'
    | '/viagens/$id'
    | '/api/public/flespi-webhook'
    | '/api/public/tracker-heartbeat'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/abastecimento'
    | '/_authenticated/ajustes'
    | '/_authenticated/despesas'
    | '/_authenticated/documentos'
    | '/_authenticated/eco'
    | '/_authenticated/gestao'
    | '/_authenticated/lugares'
    | '/_authenticated/manutencao'
    | '/_authenticated/mapa'
    | '/_authenticated/motoristas'
    | '/_authenticated/rastreador'
    | '/_authenticated/relatorio'
    | '/_authenticated/viagens'
    | '/_authenticated/'
    | '/_authenticated/viagens/$id'
    | '/api/public/flespi-webhook'
    | '/api/public/tracker-heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicFlespiWebhookRoute: typeof ApiPublicFlespiWebhookRoute
  ApiPublicTrackerHeartbeatRoute: typeof ApiPublicTrackerHeartbeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/viagens': {
      id: '/_authenticated/viagens'
      path: '/viagens'
      fullPath: '/viagens'
      preLoaderRoute: typeof AuthenticatedViagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio': {
      id: '/_authenticated/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof AuthenticatedRelatorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rastreador': {
      id: '/_authenticated/rastreador'
      path: '/rastreador'
      fullPath: '/rastreador'
      preLoaderRoute: typeof AuthenticatedRastreadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motoristas': {
      id: '/_authenticated/motoristas'
      path: '/motoristas'
      fullPath: '/motoristas'
      preLoaderRoute: typeof AuthenticatedMotoristasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencao': {
      id: '/_authenticated/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof AuthenticatedManutencaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lugares': {
      id: '/_authenticated/lugares'
      path: '/lugares'
      fullPath: '/lugares'
      preLoaderRoute: typeof AuthenticatedLugaresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestao': {
      id: '/_authenticated/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AuthenticatedGestaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eco': {
      id: '/_authenticated/eco'
      path: '/eco'
      fullPath: '/eco'
      preLoaderRoute: typeof AuthenticatedEcoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes': {
      id: '/_authenticated/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AuthenticatedAjustesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/abastecimento': {
      id: '/_authenticated/abastecimento'
      path: '/abastecimento'
      fullPath: '/abastecimento'
      preLoaderRoute: typeof AuthenticatedAbastecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/tracker-heartbeat': {
      id: '/api/public/tracker-heartbeat'
      path: '/api/public/tracker-heartbeat'
      fullPath: '/api/public/tracker-heartbeat'
      preLoaderRoute: typeof ApiPublicTrackerHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flespi-webhook': {
      id: '/api/public/flespi-webhook'
      path: '/api/public/flespi-webhook'
      fullPath: '/api/public/flespi-webhook'
      preLoaderRoute: typeof ApiPublicFlespiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/viagens/$id': {
      id: '/_authenticated/viagens/$id'
      path: '/$id'
      fullPath: '/viagens/$id'
      preLoaderRoute: typeof AuthenticatedViagensIdRouteImport
      parentRoute: typeof AuthenticatedViagensRoute
    }
  }
}

interface AuthenticatedViagensRouteChildren {
  AuthenticatedViagensIdRoute: typeof AuthenticatedViagensIdRoute
}

const AuthenticatedViagensRouteChildren: AuthenticatedViagensRouteChildren = {
  AuthenticatedViagensIdRoute: AuthenticatedViagensIdRoute,
}

const AuthenticatedViagensRouteWithChildren =
  AuthenticatedViagensRoute._addFileChildren(AuthenticatedViagensRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbastecimentoRoute: typeof AuthenticatedAbastecimentoRoute
  AuthenticatedAjustesRoute: typeof AuthenticatedAjustesRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEcoRoute: typeof AuthenticatedEcoRoute
  AuthenticatedGestaoRoute: typeof AuthenticatedGestaoRoute
  AuthenticatedLugaresRoute: typeof AuthenticatedLugaresRoute
  AuthenticatedManutencaoRoute: typeof AuthenticatedManutencaoRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedMotoristasRoute: typeof AuthenticatedMotoristasRoute
  AuthenticatedRastreadorRoute: typeof AuthenticatedRastreadorRoute
  AuthenticatedRelatorioRoute: typeof AuthenticatedRelatorioRoute
  AuthenticatedViagensRoute: typeof AuthenticatedViagensRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbastecimentoRoute: AuthenticatedAbastecimentoRoute,
  AuthenticatedAjustesRoute: AuthenticatedAjustesRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEcoRoute: AuthenticatedEcoRoute,
  AuthenticatedGestaoRoute: AuthenticatedGestaoRoute,
  AuthenticatedLugaresRoute: AuthenticatedLugaresRoute,
  AuthenticatedManutencaoRoute: AuthenticatedManutencaoRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedMotoristasRoute: AuthenticatedMotoristasRoute,
  AuthenticatedRastreadorRoute: AuthenticatedRastreadorRoute,
  AuthenticatedRelatorioRoute: AuthenticatedRelatorioRoute,
  AuthenticatedViagensRoute: AuthenticatedViagensRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicFlespiWebhookRoute: ApiPublicFlespiWebhookRoute,
  ApiPublicTrackerHeartbeatRoute: ApiPublicTrackerHeartbeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
